### ISSUE TITLE
[Engine] [User Can] Include logos from other files

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#39]
Problem is: I have multiple definitions which draw from the same logos, so I have multiple copies of the same logo definition in multiple files, all of which would need to be updated.

Would be better if I could define all the logos in one file, and then pull them in, e.g.

```toml
[files]
include.logos = "other_file.toml"
```

In this case, the whole file would be loaded as a definition, and all the logos from that file merged in with the logos in the current file.

**Comment by jcoliz** [comment]
One problem here is that the text width specified in the included file is likely to be wrong in the new file. Current ideas are:
* Discard text width from included logos, and
* Allow specifying ONLY the text width in the new file, e.g.

```toml
[logos.something]
text_width = 1.4
# title and path taken from included logos
````
