### ISSUE TITLE
[User Can] Specify that box titles should be placed by the app

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#50]
Currently, box titles are handled by the template. As we move these around more, it would be more convenient if the app could place the box titles.

The box title text container will be aligned such that its bottom in congruent with the top of the logo box, and its top is `title_height` inches above that.

This is triggered by the title_height having a value. If title_height has a value, the others will have sensible defaults.

Given: The following TOML

```toml
[render]
title_font_size = 24
title_font_name = "Segoe UI"
title_font_color = "222222"
title_height = 0.25

[[boxes]]
title = "Left side"
logos.1 = [ "zero", "zero" ]
outer = { x = 1, y = 5, width = 6, height = 4 }
```

When: Rendering the slide
Then: The words "Left side" are rendered with the specified font, centered horizontally and vertically in a box located at (1,4.75) with size (6,0.25)
