### ISSUE TITLE
[Config] Specify styles rationally

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#59]
instead of font_size and title_font_size, we should just define the style, e.g.

```toml
[style.logo]
font_size = 12
#etc

[style.box-title]
font_size = 24
#etc
```
